name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make
      
    - name: Run packaging to app tar.gz
      run: make package

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: rds.tar.gz 
        # A file, directory or wildcard pattern that describes what to upload
        path: 'rds/build/artifacts/appstore/*.tar.gz'

