name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: cd nextcloud-rds && make
      
    - name: Run packaging to app tar.gz
      run: cd nextcloud-rds && make appstore
